name: Adromeda E-commerce CI/CD
run-name: ${{github.actor}}'s workflow
on: 
  push : 
    tags: 
    - "v*"
jobs:
  build-run-andromeda:
    runs-on: ubuntu-latest
    steps:
        - name : Checkout Source Code
          uses: actions/checkout@v4

        - name : Login to Container Registry
          uses: docker/login-action@v4
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Docker App to Container Registry
          uses : docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}/andromeda:latest
            build-args: |
              VITE_API_URL=${{ vars.VITE_API_URL }}
        
        - name: Install All Deps
          run: npm i

        - name : Build app
          run: npm run build

        - name: Upload Artefact
          uses: actions/upload-artifact@v4
          with: 
            name: build-app-result
            path: dist/ 

  release-app:
    name: Realese ready app
    needs: build-run-andromeda
    runs-on: ubuntu-latest
    steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: build-app-result
            path: dist/
        
        - name: Compress artifact
          run: zip -r andromeda.zip ./*

        - name: Realese
          uses: softprops/action-gh-release@v3
          with: 
            tag_name: ${{ github.ref_name }}
            files: | 
              andromeda.zip
  
  deploy-image:
    name: "Deploy image to server"
    needs: build-run-andromeda
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd app
            docker compose pull frontend
            docker compose up frontend -d
            # docker pull ghcr.io/${{github.repository}}/andromeda:latest
            # docker rm -f andromeda
            # docker run -d -p 9302:80 --name andromeda ghcr.io/${{github.repository}}/andromeda:latest
